### ISSUE TITLE
flask api run error

### ISSUE THREAD

**Issue by guotie** [bytedance/fedlearner#653]
/api/v2/auth/users/1:

```
ERROR:root:Uncaught exception wrapper() got an unexpected keyword argument 'user_id', stack trace:
 Traceback (most recent call last):
  File "/home/guotie/.local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/guotie/.local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/guotie/.local/lib/python3.7/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/guotie/.local/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/guotie/.local/lib/python3.7/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
TypeError: wrapper() got an unexpected keyword argument 'user_id'

127.0.0.1 - - [10/Mar/2021 10:11:55] "GET /api/v2/auth/users/1 HTTP/1.0" 500 -
INFO:werkzeug:127.0.0.1 - - [10/Mar/2021 10:11:55] "GET /api/v2/auth/users/1 HTTP/1.0" 500 -
```

python 3.7

**Comment by guotie** [comment]
/api/v2/auth/users:

```
ERROR:root:Uncaught exception Object of type function is not JSON serializable, stack trace:
 Traceback (most recent call last):
  File "/home/guotie/.local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/guotie/.local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/guotie/.local/lib/python3.7/site-packages/flask_restful/__init__.py", line 472, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/home/guotie/.local/lib/python3.7/site-packages/flask_restful/__init__.py", line 501, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/home/guotie/.local/lib/python3.7/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/local/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type function is not JSON serializable

127.0.0.1 - - [10/Mar/2021 10:12:41] "GET /api/v2/auth/users HTTP/1.0" 500 -
INFO:werkzeug:127.0.0.1 - - [10/Mar/2021 10:12:41] "GET /api/v2/auth/users HTTP/1.0" 500 -
```
